[Checker] check if label.json exists, support none alarm types

diff --git a/bin/check-format b/bin/check-format
--- a/bin/check-format
+++ b/bin/check-format
@@ -4,22 +4,35 @@ set -e
 
 PROJECT_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd ../ && pwd)"
 
-for file in $(find $PROJECT_HOME -name "label.json"); do
-  echo "Checking $file"
-  tmp=$(mktemp)
-  js-beautify -s 2 -n $file > $tmp
-  diff $file $tmp ||
-  if [[ $? -ne 0 ]]; then
-    if [[ $CHECK_ONLY == "ON" ]]; then
-      echo "Failed: Please check json format"
-      echo "See error message after running js-beautify -s 2 $file"
+projects=$(ls $PROJECT_HOME/benchmark)
+for project in $projects; do
+  versions=$(ls $PROJECT_HOME/benchmark/$project)
+  for version in $versions; do
+    echo "Checking $project-$version"
+    file=$PROJECT_HOME/benchmark/$project/$version/label.json
+    if [[ $version == *"latest" || $version == *"patch" ]]; then
+      continue
+    elif [[ ! -f $file ]]; then
+      echo "Failed: label.json does not exist for $project-$version"
       exit 1
-    else
-      echo "Formatting $file"
-      cp $tmp $file
     fi
-  fi
-  $PROJECT_HOME/bin/check-schema $file
+
+    tmp=$(mktemp)
+    js-beautify -s 2 -n $file > $tmp
+    diff $file $tmp ||
+    if [[ $? -ne 0 ]]; then
+      if [[ $CHECK_ONLY == "ON" ]]; then
+        echo "Failed: Please check json format"
+        echo "See error message after running js-beautify -s 2 $file"
+        exit 1
+      else
+        echo "Formatting $file"
+        cp $tmp $file
+      fi
+    fi
+    $PROJECT_HOME/bin/check-schema $file
+
+  done
 done
 
 echo "Done"
